name: Node.js CI

on:
  release:
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
        scope: '@knuijver'
    - run: npm ci
    - run: npm version ${{ github.event.release.tag_name }}
    - run: npm run build --if-present
    - run: npm test --if-present
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}